import { useLanguage, type HalloLanguage } from "./LanguageProvider";

const text: Record<HalloLanguage, Record<string, string>> = {
  en: {
    "jobs.ready":"READY TO MOVE","jobs.greeting":"Good day","jobs.hero":"Choose a load, stay connected and deliver with confidence.","jobs.online":"You are online and receiving jobs","jobs.open":"Open loads","jobs.nearest":"Nearest","jobs.pending":"Pending","jobs.value":"Available value","jobs.market":"JOB MARKET","jobs.available":"Available loads","jobs.refresh":"Refresh","jobs.active":"Active trip in progress","jobs.activeHelp":"Finish the current trip before accepting another load. This prevents one driver or truck from being double-booked.","jobs.loading":"Finding nearby loads…","jobs.emptyTitle":"You're all caught up","jobs.emptyText":"No open loads right now. This board refreshes automatically when a customer order becomes available.","jobs.check":"Check again","jobs.status":"AVAILABLE","jobs.pickup":"Pickup","jobs.delivery":"Delivery","jobs.reserveHelp":"If you do not already have a truck assigned, HALLOTRUCK will reserve an available matching truck when you accept.","jobs.finish":"Finish active trip first","jobs.securing":"Securing load & truck…","jobs.accept":"Accept & reserve truck →","jobs.signIn":"Sign in required.","jobs.taken":"Someone else already took this load.","jobs.loadError":"Couldn't load jobs.",
    "earn.kicker":"PAYMENT-LINKED EARNINGS","earn.title":"Earnings","earn.desc":"Every released customer payment is split transparently: 2% HALLO Smart platform commission and 98% driver net earnings.","earn.releasedTrips":"Released trips","earn.gross":"Gross released","earn.commission":"HALLO Smart 2%","earn.net":"Driver net earnings","earn.pendingTrips":"Pending trips","earn.netPending":"Driver net pending","earn.partialNotice":"Partially released customer payments included in the totals above:","earn.ledger":"PAYOUT LEDGER","earn.releasedPayouts":"Released payouts","earn.trips":"trips","earn.noReleased":"No fully released payouts yet.","earn.outstanding":"OUTSTANDING","earn.pendingPayout":"Pending payout","earn.noPending":"No outstanding payout balance.","earn.how":"HOW PAYOUT WORKS","earn.howText":"Trip delivered → customer payment verified/held in escrow → Admin or Finance releases payment → HALLO Smart commission is calculated at 2% → the remaining 98% is the driver net payout.","earn.tripValue":"Trip value","earn.grossSoFar":"Gross released so far","earn.driverNet":"Driver net","earn.held":"Held in escrow","earn.netBalance":"Driver net balance","earn.payoutReleased":"Payout released","earn.delivered":"Delivered","earn.waitingVerify":"Waiting verification","earn.invoiceBalance":"Invoice balance before commission","earn.status.released":"Released","earn.status.partial":"Partially released","earn.status.held":"Held in escrow","earn.status.initiated":"Verification pending","earn.status.unpaid":"Awaiting payment","earn.error":"Could not load earnings."
  },
  om: {
    "jobs.ready":"SOCHO'UUF QOPHAA'I","jobs.greeting":"Guyyaa gaarii","jobs.hero":"Fe'umsa filadhu, wal qunnamtii keessa turi, amanamummaan geessi.","jobs.online":"Online jirta; hojii haaraa fudhachaa jirta","jobs.open":"Fe'umsa banaa","jobs.nearest":"Kan dhihoo","jobs.pending":"Eeggachaa jira","jobs.value":"Gatii hojii jiru","jobs.market":"GABAA HOJII","jobs.available":"Fe'umsa jiran","jobs.refresh":"Haaromsi","jobs.active":"Imalli tokko hojirra jira","jobs.activeHelp":"Fe'umsa biraa fudhachuu dura imala amma jiru xumuri. Kun driver ykn truck tokko yeroo tokko keessatti hojii lama irratti ramadamuu irraa eega.","jobs.loading":"Fe'umsa dhihoo barbaadaa jira…","jobs.emptyTitle":"Hojii ammaaf hin jiru","jobs.emptyText":"Amma fe'umsi banaan hin jiru. Maamilaan order haaraa yeroo godhu board kun ofumaan haaromsa.","jobs.check":"Irra deebi'ii ilaali","jobs.status":"JIRA","jobs.pickup":"Ka'umsaa","jobs.delivery":"Geessuu","jobs.reserveHelp":"Truck siif ramadame yoo hin jiraanne, fe'umsa fudhatte HALLOTRUCK truck gosa walsimu kan jiru siif reserve godha.","jobs.finish":"Dura imala jiru xumuri","jobs.securing":"Fe'umsa fi truck qabsiisaa jira…","jobs.accept":"Fudhadhu & truck reserve godhi →","jobs.signIn":"Seenuun barbaachisaa dha.","jobs.taken":"Driver biraan fe'umsa kana dursee fudhateera.","jobs.loadError":"Hojii fe'uun hin milkoofne.",
    "earn.kicker":"GALII KAFFALTII WALIIN WALQABATE","earn.title":"Galii","earn.desc":"Kaffaltiin maamilaa release ta'e ifatti qoodama: 2% commission HALLO Smart, 98% galii qulqulluu driver.","earn.releasedTrips":"Imala kaffalame","earn.gross":"Waliigala release","earn.commission":"HALLO Smart 2%","earn.net":"Galii qulqulluu driver","earn.pendingTrips":"Imala eeggachaa jiru","earn.netPending":"Galii driver eeggachaa jiru","earn.partialNotice":"Kaffaltii maamilaa gartokkoon release ta'e waliigala armaan olii keessatti dabalame:","earn.ledger":"GALMEE KAFFALTII","earn.releasedPayouts":"Kaffaltii release ta'e","earn.trips":"imala","earn.noReleased":"Kaffaltiin guutuun release ta'e amma hin jiru.","earn.outstanding":"KAN HAFE","earn.pendingPayout":"Kaffaltii eeggachaa jiru","earn.noPending":"Kaffaltiin hafe hin jiru.","earn.how":"KAFFALTIIN AKKAMITTI HOJJETA","earn.howText":"Imalli geeffame → kaffaltiin maamilaa mirkanaa'e/escrow keessa gale → Admin ykn Finance release godha → HALLO Smart 2% commission fudhata → 98% hafe galii qulqulluu driver ta'a.","earn.tripValue":"Gatii imalaa","earn.grossSoFar":"Hanga ammaatti release","earn.driverNet":"Galii qulqulluu driver","earn.held":"Escrow keessa","earn.netBalance":"Galii driver hafe","earn.payoutReleased":"Kaffaltiin release ta'e","earn.delivered":"Geeffame","earn.waitingVerify":"Mirkaneessa eeggachaa jira","earn.invoiceBalance":"Balance invoice commission dura","earn.status.released":"Release ta'e","earn.status.partial":"Gartokkoon release","earn.status.held":"Escrow keessa","earn.status.initiated":"Mirkaneessa eeggachaa","earn.status.unpaid":"Kaffaltii eeggachaa","earn.error":"Galii fe'uun hin milkoofne."
  },
  am: {
    "jobs.ready":"ለመንቀሳቀስ ዝግጁ","jobs.greeting":"መልካም ቀን","jobs.hero":"ጭነት ይምረጡ፣ ተገናኝተው ይቆዩ እና በእምነት ያድርሱ።","jobs.online":"ኦንላይን ነዎት እና ስራዎችን እየተቀበሉ ነው","jobs.open":"ክፍት ጭነቶች","jobs.nearest":"ቅርብ","jobs.pending":"በመጠበቅ ላይ","jobs.value":"ያለው ዋጋ","jobs.market":"የስራ ገበያ","jobs.available":"ያሉ ጭነቶች","jobs.refresh":"አድስ","jobs.active":"ንቁ ጉዞ አለ","jobs.activeHelp":"ሌላ ጭነት ከመቀበልዎ በፊት ያለውን ጉዞ ያጠናቅቁ። ይህ አሽከርካሪ ወይም መኪና በአንድ ጊዜ ሁለት ስራ እንዳይይዝ ይከላከላል።","jobs.loading":"በአቅራቢያ ያሉ ጭነቶችን በመፈለግ ላይ…","jobs.emptyTitle":"አሁን ስራ የለም","jobs.emptyText":"አሁን ክፍት ጭነት የለም። ደንበኛ አዲስ ትዕዛዝ ሲፈጥር ይህ ገጽ ራሱን ያድሳል።","jobs.check":"እንደገና ይፈትሹ","jobs.status":"ይገኛል","jobs.pickup":"መነሻ","jobs.delivery":"መድረሻ","jobs.reserveHelp":"የተመደበ መኪና ከሌለዎት፣ ጭነቱን ሲቀበሉ HALLOTRUCK ተስማሚ ክፍት መኪና ያስይዝልዎታል።","jobs.finish":"መጀመሪያ ንቁ ጉዞውን ያጠናቅቁ","jobs.securing":"ጭነትና መኪና በማስያዝ ላይ…","jobs.accept":"ተቀበል እና መኪና አስይዝ →","jobs.signIn":"መግባት ያስፈልጋል።","jobs.taken":"ሌላ አሽከርካሪ ይህን ጭነት ቀድሞ ወስዶታል።","jobs.loadError":"ስራዎችን መጫን አልተቻለም።",
    "earn.kicker":"ከክፍያ ጋር የተገናኘ ገቢ","earn.title":"ገቢ","earn.desc":"የተለቀቀ የደንበኛ ክፍያ በግልጽ ይከፈላል፦ 2% HALLO Smart ኮሚሽን እና 98% የአሽከርካሪ የተጣራ ገቢ።","earn.releasedTrips":"የተከፈሉ ጉዞዎች","earn.gross":"ጠቅላላ የተለቀቀ","earn.commission":"HALLO Smart 2%","earn.net":"የአሽከርካሪ የተጣራ ገቢ","earn.pendingTrips":"በመጠበቅ ላይ ያሉ ጉዞዎች","earn.netPending":"የሚጠበቅ የአሽከርካሪ ገቢ","earn.partialNotice":"በከፊል የተለቀቁ የደንበኛ ክፍያዎች ከላይ ባለው ድምር ውስጥ ተካትተዋል፦","earn.ledger":"የክፍያ መዝገብ","earn.releasedPayouts":"የተለቀቁ ክፍያዎች","earn.trips":"ጉዞዎች","earn.noReleased":"ሙሉ በሙሉ የተለቀቀ ክፍያ ገና የለም።","earn.outstanding":"ቀሪ","earn.pendingPayout":"በመጠበቅ ላይ ያለ ክፍያ","earn.noPending":"ያልተከፈለ ቀሪ የለም።","earn.how":"ክፍያው እንዴት ይሰራል","earn.howText":"ጉዞ ይጠናቀቃል → የደንበኛ ክፍያ ይረጋገጣል/በescrow ይያዛል → Admin ወይም Finance ይለቀዋል → HALLO Smart 2% ኮሚሽን ይቆጥራል → ቀሪው 98% የአሽከርካሪ የተጣራ ክፍያ ይሆናል።","earn.tripValue":"የጉዞ ዋጋ","earn.grossSoFar":"እስካሁን የተለቀቀ","earn.driverNet":"የአሽከርካሪ የተጣራ","earn.held":"በescrow የተያዘ","earn.netBalance":"የአሽከርካሪ ቀሪ","earn.payoutReleased":"ክፍያ የተለቀቀበት","earn.delivered":"የደረሰ","earn.waitingVerify":"ማረጋገጫ በመጠበቅ ላይ","earn.invoiceBalance":"ከኮሚሽን በፊት የinvoice ቀሪ","earn.status.released":"ተለቋል","earn.status.partial":"በከፊል ተለቋል","earn.status.held":"በescrow የተያዘ","earn.status.initiated":"ማረጋገጫ በመጠበቅ","earn.status.unpaid":"ክፍያ በመጠበቅ","earn.error":"ገቢን መጫን አልተቻለም።"
  }
};

export function useDriverText() {
  const { language } = useLanguage();
  return (key: string) => text[language][key] ?? text.en[key] ?? key;
}
