import type { RealtimeChannel } from "@supabase/supabase-js";
import { supabase } from "./supabase.client";
export interface CustomerDriverChatMessage{id:string;thread_id:string;sender_id:string;body:string;client_message_id:string;created_at:string}
export interface CustomerDriverChatThread{id:string;order_id:string;customer_id:string;driver_id:string;customer_last_read_at:string|null;driver_last_read_at:string|null;last_message_at:string|null;last_message_preview:string|null;last_sender_id:string|null}
export async function openCustomerDriverOrderChat(orderId:string){const{data,error}=await supabase.rpc("open_customer_driver_order_chat",{p_order_id:orderId});if(error||!data)throw new Error(error?.message||"Order chat could not be opened.");return String(data)}
export async function loadCustomerDriverChatThread(threadId:string){const{data,error}=await supabase.from("customer_driver_chat_threads").select("*").eq("id",threadId).single();if(error||!data)throw new Error(error?.message||"Order chat could not be loaded.");return data as CustomerDriverChatThread}
export async function loadCustomerDriverChatMessages(threadId:string){const{data,error}=await supabase.from("customer_driver_chat_messages").select("id,thread_id,sender_id,body,client_message_id,created_at").eq("thread_id",threadId).order("created_at",{ascending:true}).limit(300);if(error)throw new Error(error.message);return(data??[])as CustomerDriverChatMessage[]}
export async function sendCustomerDriverChatMessage(threadId:string,body:string){const text=body.trim();if(!text)return;const{error}=await supabase.rpc("send_customer_driver_chat_message",{p_thread_id:threadId,p_body:text,p_client_message_id:crypto.randomUUID()});if(error)throw new Error(error.message)}
export async function markCustomerDriverChatRead(threadId:string){const{error}=await supabase.rpc("mark_customer_driver_chat_read",{p_thread_id:threadId});if(error)throw new Error(error.message)}
export function watchCustomerDriverChat(threadId:string,onChange:()=>void):RealtimeChannel{return supabase.channel(`customer-driver-chat-${threadId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"customer_driver_chat_messages",filter:`thread_id=eq.${threadId}`},onChange).on("postgres_changes",{event:"UPDATE",schema:"public",table:"customer_driver_chat_threads",filter:`id=eq.${threadId}`},onChange).subscribe()}
