import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import'./styles.css';
type Tab='home'|'jobs'|'trip'|'wallet'|'profile';
const jobs=[['Addis Ababa','Adama','ETB 18,500','95 km'],['Adama','Dire Dawa','ETB 52,000','420 km']];
function Home({go}:{go:(t:Tab)=>void}){return <main><section className="hero"><div><small>GOOD MORNING</small><h1>Abdi Driver</h1><p>Ready for today’s trips?</p></div><span className="online">● Online</span></section><h2>Today Overview</h2><div className="metrics"><Card n="3" l="Jobs"/><Card n="1" l="Active Trip"/><Card n="95 km" l="Distance"/><Card n="ETB 8.4K" l="Earnings"/></div><div className="title"><h2>Available Jobs</h2><button onClick={()=>go('jobs')}>View all</button></div><Job j={jobs[0]} go={go}/><section className="support"><b>Smart & Reliable</b><span>Real-time tracking · Higher earnings · 24/7 support</span></section></main>}
function Card({n,l}:{n:string,l:string}){return <div className="card metric"><b>{n}</b><span>{l}</span></div>}
function Job({j,go}:{j:string[],go:(t:Tab)=>void}){return <article className="card job"><div className="price">{j[2]}</div><div className="route"><i/> <div><b>{j[0]}</b><span>Pickup</span><b>{j[1]}</b><span>Drop-off · {j[3]}</span></div></div><button className="primary" onClick={()=>go('trip')}>Accept Job</button></article>}
function Jobs({go}:{go:(t:Tab)=>void}){return <main><Header t="Available Jobs" s="Choose the best trip for you"/>{jobs.map((j,i)=><Job key={i} j={j} go={go}/>)}</main>}
function Trip(){return <main className="trip"><div className="map"><div className="mapgrid"/><div className="routeLine">●━━━━━━●</div><span className="pin a">Addis Ababa</span><span className="pin b">Adama</span></div><section className="sheet"><span className="handle"/><div className="title"><div><small>TRIP IN PROGRESS</small><h2>Addis Ababa → Adama</h2></div><button>Help</button></div><div className="metrics two"><Card n="1h 42m" l="ETA"/><Card n="63 km" l="Remaining"/></div><div className="card contact"><div className="avatar">AD</div><div><b>Customer</b><span>Order HT-2026-1042</span></div><button>Call</button><button>Chat</button></div><div className="timeline"><p className="done">✓ Pickup completed</p><p>● In transit</p><p>○ Delivery proof</p></div><button className="primary">Complete Delivery</button></section></main>}
function Wallet(){return <main><Header t="Wallet & Earnings" s="Your driver finance overview"/><section className="hero wallet"><small>AVAILABLE BALANCE</small><h1>ETB 24,850</h1><p>Commission and trip earnings updated automatically.</p></section><div className="metrics two"><Card n="ETB 8,400" l="This week"/><Card n="12" l="Completed trips"/></div><section className="card list"><h3>Recent activity</h3><p><b>Trip earning</b><span>+ ETB 4,200</span></p><p><b>Commission</b><span>− ETB 420</span></p></section></main>}
function Profile(){return <main><Header t="Driver Profile" s="Account, truck & compliance"/><section className="profile card"><div className="avatar big">AD</div><h2>Abdi Driver</h2><span className="verified">✓ Verified driver</span></section><section className="card list"><p><b>Truck</b><span>Isuzu FSR · 10 Ton</span></p><p><b>Plate</b><span>ET-3-12345</span></p><p><b>Documents</b><span className="ok">Up to date</span></p><p><b>Support</b><span>24/7</span></p></section></main>}
function Header({t,s}:{t:string,s:string}){return <header><small>HALLO DRIVER</small><h1>{t}</h1><p>{s}</p></header>}
function App(){const[tab,setTab]=useState<Tab>('home');return <div className="app">{tab==='home'?<Home go={setTab}/>:tab==='jobs'?<Jobs go={setTab}/>:tab==='trip'?<Trip/>:tab==='wallet'?<Wallet/>:<Profile/>}<nav>{([['home','⌂','Home'],['jobs','▣','Jobs'],['trip','⌖','Trip'],['wallet','◈','Wallet'],['profile','●','Profile']] as [Tab,string,string][]).map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}><b>{x[1]}</b><span>{x[2]}</span></button>)}</nav></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);