import { evaluateDriverAccess, type DriverProfile } from './driverSession';
type TokenPayload={access_token:string;refresh_token:string;expires_in?:number;user?:{id:string;email?:string|null}};
type ApprovedDriverRpc='get_available_jobs_v2'|'driver_available_trucks_for_order_v2'|'claim_order_with_truck_v2';
function config(){const env=process.env as Record<string,string|undefined>;const url=env.HALLO_AUTH_API_URL?.trim()||env.SUPABASE_URL?.trim();const key=env.HALLO_AUTH_PUBLIC_KEY?.trim()||env.SUPABASE_PUBLISHABLE_KEY?.trim();return url&&key?{url:url.replace(/\/$/,''),key}:null;}
function cookieValue(request:Request,name:string){const cookie=request.headers.get('cookie')??'';const found=cookie.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='));return found?decodeURIComponent(found.slice(name.length+1)):'';}
function cookie(name:string,value:string,maxAge:number){return name+'='+encodeURIComponent(value)+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age='+maxAge;}
async function fetchProfile(baseUrl:string,key:string,accessToken:string,userId:string):Promise<DriverProfile|null>{const response=await fetch(baseUrl+'/rest/v1/profiles?id=eq.'+encodeURIComponent(userId)+'&select=id,role,driver_status,is_active&limit=1',{headers:{apikey:key,authorization:'Bearer '+accessToken}});if(!response.ok)return null;const rows=await response.json().catch(()=>[]);return Array.isArray(rows)&&rows.length?rows[0] as DriverProfile:null;}
async function resolveSession(request:Request){const cfg=config();if(!cfg)return{configured:false as const};const accessToken=cookieValue(request,'hallo_v6_access');if(!accessToken)return{configured:true as const,access:'signed-out' as const};const userResponse=await fetch(cfg.url+'/auth/v1/user',{headers:{apikey:cfg.key,authorization:'Bearer '+accessToken}});if(!userResponse.ok)return{configured:true as const,access:'signed-out' as const};const user=await userResponse.json() as {id:string;email?:string|null};const profile=await fetchProfile(cfg.url,cfg.key,accessToken,user.id);return{configured:true as const,access:evaluateDriverAccess(user,profile),user,profile};}
async function rpcForApprovedDriver(request:Request,name:ApprovedDriverRpc,params:Record<string,unknown>={}){const cfg=config();if(!cfg)return Response.json({error:'HALLO Supabase connection is not configured yet.'},{status:503});const session=await resolveSession(request);if(!session.configured)return Response.json({error:'HALLO Supabase connection is not configured yet.'},{status:503});if(session.access==='signed-out')return Response.json({error:'Sign in is required.'},{status:401});if(session.access!=='approved')return Response.json({error:'An active approved driver account is required.'},{status:403});const token=cookieValue(request,'hallo_v6_access');const response=await fetch(cfg.url+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:cfg.key,authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(params)});const payload=await response.json().catch(()=>({}));if(!response.ok)return Response.json({error:typeof payload?.message==='string'?payload.message:'HALLO request failed.'},{status:response.status});return Response.json(payload,{status:response.status});}
export const driverSupabaseServer={config,cookie,cookieValue,fetchProfile,resolveSession,rpcForApprovedDriver,async signIn(email:string,password:string){const cfg=config();if(!cfg)return{configured:false as const};const response=await fetch(cfg.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:cfg.key,'content-type':'application/json'},body:JSON.stringify({email,password})});const body=await response.json().catch(()=>({}));if(!response.ok)return{configured:true as const,error:body?.msg||body?.error_description||'Invalid email or password.'};const tokens=body as TokenPayload;const user=tokens.user;if(!user?.id||!tokens.access_token||!tokens.refresh_token)return{configured:true as const,error:'Authentication response was incomplete.'};const profile=await fetchProfile(cfg.url,cfg.key,tokens.access_token,user.id);const access=evaluateDriverAccess(user,profile);return{configured:true as const,access,user,profile,tokens};}};
