import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { CustomerCancelOrderModal } from "../components/customer/CustomerCancelOrderModal";
import { CustomerDriverChat } from "../components/customer/CustomerDriverChat";
import { CustomerLiveTripMap } from "../components/tracking/CustomerLiveTripMap";
import { useLanguage } from "../i18n/LanguageProvider";
import { getCustomerPortalData,type CustomerDriverAssignment,type CustomerOrder } from "../services/customer.service";
import { supabase } from "../services/supabase.client";

export function CustomerTrackingPage(){const{orderId=""}=useParams();const{language}=useLanguage();const[order,setOrder]=useState<CustomerOrder|null>(null);const[assignment,setAssignment]=useState<CustomerDriverAssignment|null>(null);const[truckPhotoUrl,setTruckPhotoUrl]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[cancelOpen,setCancelOpen]=useState(false);const[chatOpen,setChatOpen]=useState(false);const[retryKey,setRetryKey]=useState(0);const text=language==="om"?{back:"Gara orders deebiʼi",call:"Bilbili",chat:"Chat",pickup:"Pickup",dropoff:"Drop-off",waiting:"Assignment verified eegamaa jira",cancel:"Ajaja kana dhiisi",verified:"Driver fi truck verified",truck:"Truck ramadame",trip:"Trip hojii irra jira",retry:"Irra deebiʼii yaali"}:language==="am"?{back:"ወደ ትዕዛዞች ተመለስ",call:"ይደውሉ",chat:"Chat",pickup:"መነሻ",dropoff:"መድረሻ",waiting:"የተረጋገጠ ምደባ በመጠበቅ ላይ",cancel:"ትዕዛዙን ሰርዝ",verified:"የተረጋገጠ አሽከርካሪና መኪና",truck:"የተመደበ መኪና",trip:"ጉዞ በሂደት ላይ",retry:"እንደገና ሞክር"}:{back:"Back to orders",call:"Call",chat:"Chat",pickup:"Pickup",dropoff:"Drop-off",waiting:"Waiting for verified assignment",cancel:"Cancel this order",verified:"Verified driver & truck",truck:"Assigned truck",trip:"Trip in progress",retry:"Retry"};
useEffect(()=>{let cancelled=false;async function load(){setLoading(true);try{const data=await getCustomerPortalData();if(cancelled)return;const current=data.orders.find(i=>i.id===orderId)??null;setOrder(current);setAssignment(data.assignments.find(i=>i.order_id===orderId)??null);setError(current?"":"Order not found.")}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"Live tracking could not be loaded.")}finally{if(!cancelled)setLoading(false)}}void load();const timer=window.setInterval(()=>void load(),10000);return()=>{cancelled=true;clearInterval(timer)}},[orderId,retryKey]);
useEffect(()=>{let cancelled=false;const path=assignment?.truck_photo_path;if(!path){setTruckPhotoUrl(null);return}void supabase.storage.from("driver-verification").createSignedUrl(path,3600).then(({data,error})=>{if(!cancelled)setTruckPhotoUrl(error?null:data?.signedUrl??null)});return()=>{cancelled=true}},[assignment?.truck_photo_path]);
const initials=useMemo(()=>{const parts=(assignment?.driver_name??"Driver").trim().split(/\s+/).slice(0,2);return parts.map(p=>p[0]?.toUpperCase()??"").join("")||"DR"},[assignment?.driver_name]);const trackable=order&&["accepted","in_transit","delivered"].includes(order.status);const cancellable=order&&["quoted","placed","accepted","in_transit"].includes(order.status);
return <main className="customer-live-page"><header className="customer-live-page__header"><Link to="/customer/orders" aria-label={text.back}>←</Link><div><p>LIVE CARGO TRACKING</p><h1>{order?.tracking_id??(loading?"Loading…":"HALLOTRUCK")}</h1></div><span className="customer-live-page__badge">● Live</span></header><section className="customer-live-page__content">{error&&<div className="customer-nearby-sheet__error"><p>{error}</p><button onClick={()=>setRetryKey((key) => key + 1)}>{text.retry}</button></div>}{order&&<>{assignment&&order.status!=="cancelled"&&<article className="customer-live-page__truck-card"><div className="customer-live-page__truck-photo">{truckPhotoUrl?<img src={truckPhotoUrl} alt={text.truck}/>:<span>🚚</span>}</div><div className="customer-live-page__truck-copy"><small>{text.truck}</small><h2>{assignment.vehicle_type??order.vehicle_type}</h2><p>{assignment.plate_number??"—"} · {assignment.capacity_tons==null?"—":`${assignment.capacity_tons} ton`}</p></div><span className={`customer-live-page__truck-state${trackable?" is-live":""}`}>{trackable?text.trip:text.truck}</span></article>}{assignment&&order.status!=="cancelled"&&<article className="customer-live-page__driver"><div className="customer-live-page__avatar">{initials}</div><div><h2>{assignment.driver_name}</h2><p>{text.verified}</p><small>{assignment.plate_number??"Plate pending"}</small></div><div className="customer-live-page__driver-actions">{assignment.driver_phone&&<a href={`tel:${assignment.driver_phone}`}>{text.call}</a>}<button type="button" onClick={()=>setChatOpen(true)}>💬 {text.chat}</button></div></article>}<article className="customer-live-page__route"><span/><div><strong>{order.pickup_address}</strong><small>{text.pickup}</small></div><span/><div><strong>{order.dropoff_address}</strong><small>{text.dropoff}</small></div></article>{cancellable&&<button className="customer-live-page__cancel-order" onClick={()=>setCancelOpen(true)}>{text.cancel}</button>}{assignment&&trackable?<article className="customer-live-page__map-shell"><CustomerLiveTripMap orderId={order.id} totalDistanceKm={order.distance_km} standalone/></article>:<article className="customer-live-page__waiting"><h2>{text.waiting}</h2></article>}</>}</section>{chatOpen&&order&&assignment&&<CustomerDriverChat orderId={order.id} driverName={assignment.driver_name} onClose={()=>setChatOpen(false)}/>} {cancelOpen&&order&&<CustomerCancelOrderModal order={order} onClose={()=>setCancelOpen(false)} onCancelled={async()=>{setCancelOpen(false);setRetryKey(k=>k+1)}}/>}</main>}
