const LANGUAGE_KEY = "hallo-customer-language";
const LANGUAGE_EVENT = "hallo-customer-language-change";

const COPY: Record<"om" | "am", Record<string, string>> = {
  om: {
    "PICKUP PLACE":"BAKKA KAʼUMSAA","DROP-OFF PLACE":"BAKKA GEESSUMSAA","Find pickup place":"Bakka kaʼumsaa barbaadi","Find delivery place":"Bakka geessumsaa barbaadi","My location":"Bakka koo","Locating…":"Bakka kee barbaadaa…","Swap":"Wal jijjiiri","Reset":"Haqi","Start your booking":"Booking jalqabi","Search, use your location, or tap the map to choose pickup and drop-off.":"Barbaadi, bakka kee fayyadami, ykn bakka kaʼumsaa fi geessumsaa filachuuf kaartaa tuqi.","Continue":"Itti fufi","Truck route ready":"Daandiin konkolaataa qophaaʼeera","Route selected":"Daandiin filatameera","Calculating truck route…":"Daandii konkolaataa shallagaa jira…","Truck route unavailable":"Daandiin konkolaataa hin argamne","AUTO DISTANCE":"FAGEENYA OFUMAA",
    "Home":"Mana","Orders":"Ajajawwan","Track":"Hordofi","Payments":"Kaffaltii","Profile":"Profaayilii","New order":"Ajaja haaraa","Refresh":"Haaromsi","Retry":"Irra deebiʼi","Try again":"Irra deebiʼi","Go to Home":"Gara Manaatti","Back to Orders":"Gara Ajajawwaniitti","Secure DB":"Kuusaa nageenya qabu",
    "Loading orders…":"Ajajawwan feʼaa jira…","Orders could not be loaded":"Ajajawwan feʼamuu hin dandeenye","No orders yet":"Ajajni amma hin jiru","Start a new transport order from Home.":"Ajaja geejjibaa haaraa Mana irraa jalqabi.","Refresh tracking":"Hordoffii haaromsi","Refreshing…":"Haaromsaa jira…","Loading live tracking…":"Hordoffii kallattii feʼaa jira…","Live tracking could not be loaded":"Hordoffiin kallattii feʼamuu hin dandeenye","No active trip":"Geejjibni sochoʼaa hin jiru","TRACKING / ORDER ID":"HORDOFFII / LAKKOOFSA AJAJAA","Pickup":"Kaʼumsa","Drop-off":"Geessumsa","Pickup pending":"Kaʼumsi eegamaa jira","Drop-off pending":"Geessumsi eegamaa jira","Choose active trip":"Geejjiba sochoʼaa fili","GPS SNAPSHOT":"HAALA GPS","Waiting for GPS":"GPS eegamaa jira","Live Driver GPS":"GPS konkolaachisaa kallattii","Last GPS update":"GPS yeroo dhumaa haaromfame","Waiting for GPS update":"Haaromsa GPS eegamaa jira","STALE · last known location":"DULLOOME · bakka dhumaa beekame","OFFLINE · last known location":"SARARA ALA · bakka dhumaa beekame",
    "ASSIGNED DRIVER & TRUCK":"KONKOLAACHISAA FI KONKOLAATAA RAMADAME","ASSIGNMENT PENDING":"RAMADAMNI EEGGAMAA JIRA","✓ VERIFIED DRIVER":"✓ KONKOLAACHISAA MIRKANAAʼE","VERIFICATION PENDING":"MIRKANEESSI EEGGAMAA JIRA","TRUCK":"KONKOLAATAA","DRIVER":"KONKOLAACHISAA","Plate pending":"Lakkoofsi gabatee eegamaa jira","Assigned Driver":"Konkolaachisaa ramadame","Phone unavailable":"Bilbilli hin jiru","Loading photo…":"Suuraa feʼaa jira…","Live trip tracking →":"Geejjiba kallattiin hordofi →",
    "CUSTOMER PROFILE":"PROFAAYILII MAAMILAA","Verified Customer":"Maamila mirkanaaʼe","YOUR ACCOUNT":"AKKAAWUNTII KEE","Individual account":"Akkaawuntii dhuunfaa","Business account":"Akkaawuntii daldalaa","PROFILE PHOTO":"SUURAA PROFAAYILII","Add a Customer photo":"Suuraa maamilaa dabali","Camera":"Kaameraa","Photo library":"Kuusaa suuraa","Remove photo":"Suuraa haqi","PROFILE DETAILS":"ODEEFFANNOO PROFAAYILII","Contact & account":"Quunnamtii fi akkaawuntii","Edit profile":"Profaayilii gulaali","Cancel":"Dhiisi","Full name":"Maqaa guutuu","Phone":"Bilbila","Email":"Imeelii","Home address":"Teessoo mana","Account type":"Gosa akkaawuntii","Company":"Dhaabbata","Joined":"Guyyaa makame","Individual":"Dhuunfaa","Business":"Daldalaa","Save profile":"Profaayilii kuusi","Saving…":"Kuusaa jira…","Refresh profile":"Profaayilii haaromsi","Sign out":"Baʼi","Signing out…":"Baʼaa jira…","Loading profile…":"Profaayilii feʼaa jira…","Customer profile not available":"Profaayiliin maamilaa hin argamne",
    "Customer Payments":"Kaffaltii Maamilaa","Loading payments…":"Kaffaltii feʼaa jira…","Payments could not be loaded":"Kaffaltiin feʼamuu hin dandeenye","No payment history":"Seenaa kaffaltii hin jiru","No payment records yet":"Galmeen kaffaltii amma hin jiru","PAYMENT HISTORY":"SEENAA KAFFALTII","Your payments":"Kaffaltii kee","ORDER":"AJAJA","Amount":"Hanga","Provider":"Dhiyeessaa","Reference":"Wabii","Recorded":"Galmaaʼe","Open receipt":"Nagahee bani","Preparing receipt…":"Nagahee qopheessaa jira…","Assigned":"Ramadame","Pickup":"Kaʼumsa","On route":"Daandii irra","Delivered":"Geessame","Trip status":"Haala geejjibaa","Truck GPS":"GPS konkolaataa","Remaining distance":"Fageenya hafe","ETA":"Yeroo tilmaamame","Trip complete":"Geejjibni xumurame","Loading map…":"Kaartaa feʼaa jira…","Loading route…":"Daandii feʼaa jira…","Latest location timestamp":"Yeroo bakka dhumaa","Call":"Bilbili","Chat":"Ergaa","Refresh tracking":"Hordoffii haaromsi","LIVE TRIP TRACKING":"HORDOFFII GEEJJIBAA KALLATTII","Read-only Customer tracking. GPS writes remain Driver-only; assignment and trip access stay bound to this signed-in Customer's order.":"Hordoffii Maamilaa dubbisuu qofa. GPS Konkolaachisaa qofa irraa galmaaʼa; ramaddii fi geejjibni ajaja Maamila seene kana qofa waliin hidhata.","Private assignment details are shown only for this signed-in Customer's order.":"Ibsi ramaddii dhuunfaa ajaja Maamila seene kanaaf qofa mulʼata."
  },
  am: {
    "PICKUP PLACE":"መነሻ ቦታ","DROP-OFF PLACE":"መድረሻ ቦታ","Find pickup place":"መነሻ ቦታ ይፈልጉ","Find delivery place":"መድረሻ ቦታ ይፈልጉ","My location":"የእኔ ቦታ","Locating…":"ቦታዎን በመፈለግ ላይ…","Swap":"ቀያይር","Reset":"አጽዳ","Start your booking":"ትዕዛዝዎን ይጀምሩ","Search, use your location, or tap the map to choose pickup and drop-off.":"ይፈልጉ፣ ያሉበትን ቦታ ይጠቀሙ ወይም መነሻና መድረሻን ለመምረጥ ካርታውን ይንኩ።","Continue":"ቀጥል","Truck route ready":"የመኪና መንገድ ዝግጁ ነው","Route selected":"መንገድ ተመርጧል","Calculating truck route…":"የመኪና መንገድ በማስላት ላይ…","Truck route unavailable":"የመኪና መንገድ አልተገኘም","AUTO DISTANCE":"ራስ-ሰር ርቀት",
    "Home":"መነሻ","Orders":"ትዕዛዞች","Track":"ክትትል","Payments":"ክፍያዎች","Profile":"መገለጫ","New order":"አዲስ ትዕዛዝ","Refresh":"አድስ","Retry":"እንደገና ሞክር","Try again":"እንደገና ሞክር","Go to Home":"ወደ መነሻ","Back to Orders":"ወደ ትዕዛዞች","Secure DB":"ደህንነቱ የተጠበቀ ዳታ",
    "Loading orders…":"ትዕዛዞች በመጫን ላይ…","Orders could not be loaded":"ትዕዛዞችን መጫን አልተቻለም","No orders yet":"ገና ትዕዛዝ የለም","Start a new transport order from Home.":"ከመነሻ አዲስ የመጓጓዣ ትዕዛዝ ይጀምሩ።","Refresh tracking":"ክትትልን አድስ","Refreshing…":"በማደስ ላይ…","Loading live tracking…":"ቀጥታ ክትትል በመጫን ላይ…","Live tracking could not be loaded":"ቀጥታ ክትትልን መጫን አልተቻለም","No active trip":"ንቁ ጉዞ የለም","TRACKING / ORDER ID":"ክትትል / የትዕዛዝ መለያ","Pickup":"መነሻ","Drop-off":"መድረሻ","Pickup pending":"መነሻ በመጠባበቅ ላይ","Drop-off pending":"መድረሻ በመጠባበቅ ላይ","Choose active trip":"ንቁ ጉዞ ይምረጡ","GPS SNAPSHOT":"የGPS ሁኔታ","Waiting for GPS":"GPS በመጠባበቅ ላይ","Live Driver GPS":"የአሽከርካሪ ቀጥታ GPS","Last GPS update":"የመጨረሻ GPS ዝመና","Waiting for GPS update":"የGPS ዝመና በመጠባበቅ ላይ","STALE · last known location":"ያረጀ · የመጨረሻ የታወቀ ቦታ","OFFLINE · last known location":"ከመስመር ውጭ · የመጨረሻ የታወቀ ቦታ",
    "ASSIGNED DRIVER & TRUCK":"የተመደበ አሽከርካሪ እና መኪና","ASSIGNMENT PENDING":"ምደባ በመጠባበቅ ላይ","✓ VERIFIED DRIVER":"✓ የተረጋገጠ አሽከርካሪ","VERIFICATION PENDING":"ማረጋገጫ በመጠባበቅ ላይ","TRUCK":"መኪና","DRIVER":"አሽከርካሪ","Plate pending":"ታርጋ በመጠባበቅ ላይ","Assigned Driver":"የተመደበ አሽከርካሪ","Phone unavailable":"ስልክ አልተገኘም","Loading photo…":"ፎቶ በመጫን ላይ…","Live trip tracking →":"ቀጥታ ጉዞን ይከታተሉ →",
    "CUSTOMER PROFILE":"የደንበኛ መገለጫ","Verified Customer":"የተረጋገጠ ደንበኛ","YOUR ACCOUNT":"የእርስዎ መለያ","Individual account":"የግል መለያ","Business account":"የንግድ መለያ","PROFILE PHOTO":"የመገለጫ ፎቶ","Add a Customer photo":"የደንበኛ ፎቶ ያክሉ","Camera":"ካሜራ","Photo library":"የፎቶ ማከማቻ","Remove photo":"ፎቶ አስወግድ","PROFILE DETAILS":"የመገለጫ ዝርዝር","Contact & account":"እውቂያ እና መለያ","Edit profile":"መገለጫ አርትዕ","Cancel":"ሰርዝ","Full name":"ሙሉ ስም","Phone":"ስልክ","Email":"ኢሜይል","Home address":"የቤት አድራሻ","Account type":"የመለያ አይነት","Company":"ድርጅት","Joined":"የተቀላቀሉበት","Individual":"ግለሰብ","Business":"ንግድ","Save profile":"መገለጫ አስቀምጥ","Saving…":"በማስቀመጥ ላይ…","Refresh profile":"መገለጫ አድስ","Sign out":"ውጣ","Signing out…":"በመውጣት ላይ…","Loading profile…":"መገለጫ በመጫን ላይ…","Customer profile not available":"የደንበኛ መገለጫ አልተገኘም",
    "Customer Payments":"የደንበኛ ክፍያዎች","Loading payments…":"ክፍያዎች በመጫን ላይ…","Payments could not be loaded":"ክፍያዎችን መጫን አልተቻለም","No payment history":"የክፍያ ታሪክ የለም","No payment records yet":"ገና የክፍያ መዝገብ የለም","PAYMENT HISTORY":"የክፍያ ታሪክ","Your payments":"ክፍያዎችዎ","ORDER":"ትዕዛዝ","Amount":"መጠን","Provider":"አቅራቢ","Reference":"ማጣቀሻ","Recorded":"የተመዘገበ","Open receipt":"ደረሰኝ ክፈት","Preparing receipt…":"ደረሰኝ በማዘጋጀት ላይ…","Assigned":"ተመድቧል","Pickup":"መነሻ","On route":"በመንገድ ላይ","Delivered":"ደርሷል","Trip status":"የጉዞ ሁኔታ","Truck GPS":"የመኪና GPS","Remaining distance":"የቀረ ርቀት","ETA":"የመድረሻ ጊዜ","Trip complete":"ጉዞው ተጠናቋል","Loading map…":"ካርታ በመጫን ላይ…","Loading route…":"መንገድ በመጫን ላይ…","Latest location timestamp":"የመጨረሻ ቦታ ጊዜ","Call":"ይደውሉ","Chat":"መልዕክት","Refresh tracking":"ክትትልን አድስ","LIVE TRIP TRACKING":"ቀጥታ የጉዞ ክትትል","Read-only Customer tracking. GPS writes remain Driver-only; assignment and trip access stay bound to this signed-in Customer's order.":"የደንበኛ ክትትል ለማየት ብቻ ነው። GPS የሚመዘገበው በአሽከርካሪ ብቻ ሲሆን ምደባና ጉዞ ከዚህ የገባ ደንበኛ ትዕዛዝ ጋር ብቻ የተያያዙ ናቸው።","Private assignment details are shown only for this signed-in Customer's order.":"የግል የምደባ ዝርዝር ለዚህ የገባ ደንበኛ ትዕዛዝ ብቻ ይታያል።"
  }
};

function language(): "en" | "om" | "am" { const value=window.localStorage.getItem(LANGUAGE_KEY); return value==="en"||value==="am"||value==="om"?value:"om"; }
function translateSurface(){ const lang=language(); if(lang==="en") return; const root=document.getElementById("root"); if(!root)return; const copy=COPY[lang]; const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); let node:Node|null=walker.nextNode(); while(node){const raw=node.textContent??"";const trimmed=raw.trim();const translated=copy[trimmed];if(translated)node.textContent=raw.replace(trimmed,translated);node=walker.nextNode();}}
if(typeof document!=="undefined"){const root=document.getElementById("root");if(root){const observer=new MutationObserver(translateSurface);observer.observe(root,{childList:true,subtree:true,characterData:true});}window.addEventListener(LANGUAGE_EVENT,()=>queueMicrotask(translateSurface));window.addEventListener("storage",translateSurface);queueMicrotask(translateSurface);}

export {};
