import type { CustomerLanguage } from "./customer-language";

export const customerFinalCopy = {
  en: {
    greeting: "Hello", homeQuestion: "What would you like to do today?", bookTruck: "Book a Truck", instantQuote: "Get instant quote",
    trackOrder: "Track Order", myOrders: "My Orders", payments: "Payments", savedLocations: "Saved Locations", myQuotes: "My Quotes", support: "Support",
    recentOrders: "Recent Orders", viewAll: "View All", noRecentOrders: "No orders yet", startFirstBooking: "Create your first transport booking.",
    routeTitle: "Book a Truck", route: "Route", cargo: "Cargo", truck: "Truck", quote: "Quote", review: "Review",
    pickup: "Pickup", dropoff: "Drop-off", routeReady: "Route ready", continue: "Continue", back: "Back", next: "Next",
    cargoTitle: "Cargo Details", cargoType: "Cargo Type", totalWeight: "Total Weight", packagingType: "Packaging Type",
    loadDescription: "Load Description (Optional)", specialRequirements: "Special Requirements (Optional)", loadPlaceholder: "e.g. machinery, construction material…",
    requirementsPlaceholder: "e.g. fragile, temperature control…", chooseTruck: "Choose a Truck", all: "All", maxLoad: "Max load",
    selected: "Selected", yourQuote: "Your Quote", authoritativeQuote: "Authoritative transport quote", quoteNote: "Final price is returned by HALLO secure pricing and is rechecked before booking.",
    total: "Total", calculateQuote: "Calculate Quote", calculating: "Calculating…", reviewBooking: "Review Booking", paymentMethod: "Payment Method",
    payOnDelivery: "Pay on Delivery", bankTelebirr: "Bank / Telebirr", termsAgree: "I agree to the Terms & Conditions", confirmBooking: "Confirm Booking",
    creatingOrder: "Creating order…", bookingConfirmed: "Booking Confirmed!", orderCreated: "Your order has been created successfully.",
    orderNumber: "Order Number", totalAmount: "Total Amount", viewOrder: "View Order", createAnother: "Create Another Booking",
    orderDetails: "Order Details", created: "Created", liveTracking: "Live Tracking", downloadInvoice: "Download Invoice", callDriver: "Call Driver",
    savedTitle: "Saved Locations", homeAddress: "Home", noHomeAddress: "No home address saved in your Customer profile.", editProfileToSave: "Edit your profile to add or update your home address.",
    helpTitle: "Help & Support", faq: "FAQ", faqHelp: "Answers about booking, tracking and payments.", contactUs: "Contact Us",
    contactHelp: "Use secure Driver chat on an assigned order for trip communication.", reportIssue: "Report an Issue", reportHelp: "Use the order details and tracking screens to capture the exact order context.",
    safetyTips: "Safety Tips", safetyHelp: "Confirm the verified Driver and truck details before handover.", termsPrivacy: "Terms & Privacy", termsHelp: "Your Customer data remains protected by the existing authenticated access rules.",
    settingsTitle: "Settings", language: "Language", english: "English", oromo: "Afaan Oromoo", amharic: "Amharic", appSettings: "App Settings",
    notifications: "Notifications", notificationsHelp: "Notification behavior follows your browser and HALLO account configuration.", appearance: "Appearance",
    appearanceHelp: "The approved light Customer App design is active.", privacy: "Privacy", privacyHelp: "Customer data is read through your signed-in session and existing RLS.",
    about: "About", aboutHelp: "HALLO Smart Logistics Customer App", paymentHistory: "Payment History", invoices: "Invoices", refunds: "Refunds",
    paymentLedger: "Payment ledger", paymentTruth: "Real payment events only — no fabricated wallet balance.", noPaymentRecords: "No payment records yet.",
    profileMenu: "Account", personalInformation: "Personal Information", savedAddresses: "Saved Addresses", languageSettings: "Language & Settings", helpSupport: "Help & Support",
    status: "Status", distance: "Distance", load: "Load", vehicle: "Vehicle", payment: "Payment", driverTruck: "Assigned Driver & Truck",
    openDetails: "Open details", loading: "Loading…", retry: "Retry", close: "Close", refresh: "Refresh", pending: "Pending",
    stepRouteHelp: "Choose real pickup and drop-off locations on the map.", stepCargoHelp: "Describe the load and enter its real weight.",
    stepTruckHelp: "Choose a vehicle whose capacity fits the load.", stepQuoteHelp: "Review the current server-calculated ETB quote.",
    stepReviewHelp: "Confirm route, cargo, truck, payment and terms.", weightRequired: "Enter a load amount greater than zero.",
    weightExceeds: "The load exceeds this truck's capacity.", termsRequired: "Accept the Terms & Conditions before confirming.",
    quoteChanged: "The transport price changed. Review the refreshed quote and confirm again.", noFakeData: "Nothing is estimated or invented on this screen."
  },
  om: {
    greeting: "Akkam", homeQuestion: "Har'a maal hojjechuu barbaadda?", bookTruck: "Konkolaataa Ajadhu", instantQuote: "Gatii battalaa argadhu",
    trackOrder: "Ajaja Hordofi", myOrders: "Ajajawwan Koo", payments: "Kaffaltii", savedLocations: "Bakkawwan Kuufaman", myQuotes: "Gatiiwwan Koo", support: "Deeggarsa",
    recentOrders: "Ajajawwan Dhihoo", viewAll: "Hunda Ilaali", noRecentOrders: "Ajajni amma hin jiru", startFirstBooking: "Ajaja geejjibaa kee isa jalqabaa uumi.",
    routeTitle: "Konkolaataa Ajadhu", route: "Daandii", cargo: "Fe'umsa", truck: "Konkolaataa", quote: "Gatii", review: "Mirkaneessa",
    pickup: "Ka'umsa", dropoff: "Geessumsa", routeReady: "Daandiin qophaa'eera", continue: "Itti fufi", back: "Duubatti", next: "Itti aanu",
    cargoTitle: "Ibsa Fe'umsaa", cargoType: "Gosa Fe'umsaa", totalWeight: "Ulfaatina Waliigalaa", packagingType: "Akkaataa Kuusaa",
    loadDescription: "Ibsa Fe'umsaa (Filannoo)", specialRequirements: "Barbaachisummaa Addaa (Filannoo)", loadPlaceholder: "fkn. maashinii, meeshaa ijaarsaa…",
    requirementsPlaceholder: "fkn. salphaatti caba, ho'a to'annaa…", chooseTruck: "Konkolaataa Fili", all: "Hunda", maxLoad: "Fe'umsa olaanaa",
    selected: "Filatame", yourQuote: "Gatii Kee", authoritativeQuote: "Gatii geejjibaa sirrii", quoteNote: "Gatiin dhumaa pricing nageenya qabu HALLO irraa deebi'a; ajaja dura irra deebi'ee mirkanaa'a.",
    total: "Waliigala", calculateQuote: "Gatii Shallagi", calculating: "Shallagaa jira…", reviewBooking: "Ajaja Mirkaneessi", paymentMethod: "Mala Kaffaltii",
    payOnDelivery: "Yeroo Geessan Kaffali", bankTelebirr: "Baankii / Telebirr", termsAgree: "Ulaagaa fi Haala irratti walii gala", confirmBooking: "Ajaja Mirkaneessi",
    creatingOrder: "Ajaja uumamaa jira…", bookingConfirmed: "Ajajni Mirkanaa'e!", orderCreated: "Ajajni kee milkaa'inaan uumameera.",
    orderNumber: "Lakkoofsa Ajajaa", totalAmount: "Gatii Waliigalaa", viewOrder: "Ajaja Ilaali", createAnother: "Ajaja Biraa Uumi",
    orderDetails: "Ibsa Ajajaa", created: "Uumame", liveTracking: "Kallattiin Hordofi", downloadInvoice: "Invoice Buufadhu", callDriver: "Konkolaachisaa Bilbili",
    savedTitle: "Bakkawwan Kuufaman", homeAddress: "Mana", noHomeAddress: "Teessoon mana profaayilii Customer keessatti hin kuufamne.", editProfileToSave: "Teessoo mana dabaluuf ykn haaromsuuf profaayilii sirreessi.",
    helpTitle: "Gargaarsa fi Deeggarsa", faq: "Gaaffilee Yeroo Baay'ee", faqHelp: "Ajaja, hordoffii fi kaffaltii irratti deebii gabaabaa.",
    contactUs: "Nu Qunnami", contactHelp: "Geejjiba irratti qunnamtiif ajaja ramadame keessaa chat nageenya qabu fayyadami.", reportIssue: "Rakkoo Beeksisi", reportHelp: "Ajaja sirrii adda baasuuf ibsa ajajaa fi hordoffii fayyadami.",
    safetyTips: "Gorsa Nageenyaa", safetyHelp: "Fe'umsa kennuu dura konkolaachisaa fi konkolaataa mirkanaa'e ilaali.", termsPrivacy: "Ulaagaa fi Dhuunfaa", termsHelp: "Odeeffannoon Customer seera seensaa fi RLS ammaa jalatti eegama.",
    settingsTitle: "Qindaa'ina", language: "Afaan", english: "English", oromo: "Afaan Oromoo", amharic: "አማርኛ", appSettings: "Qindaa'ina App",
    notifications: "Beeksisa", notificationsHelp: "Beeksisni qindaa'ina browser fi akkaawuntii HALLO hordofa.", appearance: "Bifa",
    appearanceHelp: "Bifni ifaa Customer App ragga'e hojiirra jira.", privacy: "Dhuunfaa", privacyHelp: "Odeeffannoon Customer session kee fi RLS jiru qofaan dubbifama.",
    about: "Waa'ee", aboutHelp: "HALLO Smart Logistics Customer App", paymentHistory: "Seenaa Kaffaltii", invoices: "Invoice", refunds: "Deebii Maallaqaa",
    paymentLedger: "Galmee kaffaltii", paymentTruth: "Kaffaltii dhugaa database keessa jiru qofa — balance sobaa hin agarsiifamu.", noPaymentRecords: "Galmeen kaffaltii amma hin jiru.",
    profileMenu: "Akkaawuntii", personalInformation: "Odeeffannoo Dhuunfaa", savedAddresses: "Teessoo Kuufame", languageSettings: "Afaan fi Qindaa'ina", helpSupport: "Gargaarsa fi Deeggarsa",
    status: "Haala", distance: "Fageenya", load: "Fe'umsa", vehicle: "Konkolaataa", payment: "Kaffaltii", driverTruck: "Konkolaachisaa fi Konkolaataa Ramadame",
    openDetails: "Ibsa bani", loading: "Fe'aa jira…", retry: "Irra deebi'i", close: "Cufi", refresh: "Haaromsi", pending: "Eegamaa",
    stepRouteHelp: "Kaartaa irratti bakka ka'umsaa fi geessumsa dhugaa fili.", stepCargoHelp: "Fe'umsa ibsi; ulfaatina isaa sirrii galchi.",
    stepTruckHelp: "Konkolaataa capacity fe'umsa kee baatu fili.", stepQuoteHelp: "Gatii ETB server irraa shallagame ilaali.",
    stepReviewHelp: "Daandii, fe'umsa, konkolaataa, kaffaltii fi ulaagaalee mirkaneessi.", weightRequired: "Baay'ina fe'umsaa zeeroo caalu galchi.",
    weightExceeds: "Fe'umsi kun capacity konkolaataa kanaa caala.", termsRequired: "Ajaja mirkaneessuuf Ulaagaa fi Haala irratti walii gali.",
    quoteChanged: "Gatiin geejjibaa jijjiirameera. Gatii haarome ilaalii irra deebi'ii mirkaneessi.", noFakeData: "Fuula kana irratti odeeffannoon hin tilmaamamu ykn hin uumamu."
  },
  am: {
    greeting: "ሰላም", homeQuestion: "ዛሬ ምን ማድረግ ይፈልጋሉ?", bookTruck: "መኪና ይያዙ", instantQuote: "ፈጣን ዋጋ ያግኙ",
    trackOrder: "ትዕዛዝ ይከታተሉ", myOrders: "ትዕዛዞቼ", payments: "ክፍያዎች", savedLocations: "የተቀመጡ ቦታዎች", myQuotes: "ዋጋዎቼ", support: "ድጋፍ",
    recentOrders: "የቅርብ ጊዜ ትዕዛዞች", viewAll: "ሁሉን ይመልከቱ", noRecentOrders: "እስካሁን ትዕዛዝ የለም", startFirstBooking: "የመጀመሪያዎን የመጓጓዣ ትዕዛዝ ይፍጠሩ።",
    routeTitle: "መኪና ይያዙ", route: "መንገድ", cargo: "ጭነት", truck: "መኪና", quote: "ዋጋ", review: "ማረጋገጫ",
    pickup: "መነሻ", dropoff: "መድረሻ", routeReady: "መንገዱ ዝግጁ ነው", continue: "ቀጥል", back: "ተመለስ", next: "ቀጣይ",
    cargoTitle: "የጭነት ዝርዝር", cargoType: "የጭነት ዓይነት", totalWeight: "ጠቅላላ ክብደት", packagingType: "የማሸጊያ ዓይነት",
    loadDescription: "የጭነት መግለጫ (አማራጭ)", specialRequirements: "ልዩ መስፈርቶች (አማራጭ)", loadPlaceholder: "ለምሳሌ፣ ማሽን፣ የግንባታ እቃ…",
    requirementsPlaceholder: "ለምሳሌ፣ ተሰባሪ፣ የሙቀት ቁጥጥር…", chooseTruck: "መኪና ይምረጡ", all: "ሁሉም", maxLoad: "ከፍተኛ ጭነት",
    selected: "ተመርጧል", yourQuote: "የእርስዎ ዋጋ", authoritativeQuote: "የተረጋገጠ የመጓጓዣ ዋጋ", quoteNote: "የመጨረሻው ዋጋ ከHALLO የደህንነት ዋጋ ስርዓት ይመጣል፣ ከትዕዛዝ በፊትም ደግሞ ይረጋገጣል።",
    total: "ጠቅላላ", calculateQuote: "ዋጋ አስላ", calculating: "በማስላት ላይ…", reviewBooking: "ትዕዛዝ ይገምግሙ", paymentMethod: "የክፍያ ዘዴ",
    payOnDelivery: "ሲደርስ ይክፈሉ", bankTelebirr: "ባንክ / ቴሌብር", termsAgree: "በውሎች እና ሁኔታዎች እስማማለሁ", confirmBooking: "ትዕዛዝ ያረጋግጡ",
    creatingOrder: "ትዕዛዝ በመፍጠር ላይ…", bookingConfirmed: "ትዕዛዙ ተረጋግጧል!", orderCreated: "ትዕዛዝዎ በተሳካ ሁኔታ ተፈጥሯል።",
    orderNumber: "የትዕዛዝ ቁጥር", totalAmount: "ጠቅላላ መጠን", viewOrder: "ትዕዛዝ ይመልከቱ", createAnother: "ሌላ ትዕዛዝ ይፍጠሩ",
    orderDetails: "የትዕዛዝ ዝርዝር", created: "የተፈጠረበት", liveTracking: "ቀጥታ ክትትል", downloadInvoice: "ኢንቮይስ ያውርዱ", callDriver: "አሽከርካሪውን ይደውሉ",
    savedTitle: "የተቀመጡ ቦታዎች", homeAddress: "መኖሪያ", noHomeAddress: "በCustomer መገለጫዎ ውስጥ የተቀመጠ የቤት አድራሻ የለም።", editProfileToSave: "የቤት አድራሻ ለመጨመር ወይም ለማዘመን መገለጫዎን ያርትዑ።",
    helpTitle: "እገዛ እና ድጋፍ", faq: "ተደጋጋሚ ጥያቄዎች", faqHelp: "ስለ ትዕዛዝ፣ ክትትል እና ክፍያ መልሶች።", contactUs: "ያግኙን",
    contactHelp: "ለጉዞ ግንኙነት በተመደበ ትዕዛዝ ላይ ያለውን የደህንነት ውይይት ይጠቀሙ።", reportIssue: "ችግኝ ሪፖርት ያድርጉ", reportHelp: "ትክክለኛውን ትዕዛዝ ለመለየት የትዕዛዝ ዝርዝርን እና ክትትልን ይጠቀሙ።",
    safetyTips: "የደህንነት ምክሮች", safetyHelp: "ጭነት ከማስረከብዎ በፊት የተረጋገጠውን አሽከርካሪና መኪና ያረጋግጡ።", termsPrivacy: "ውሎች እና ግላዊነት", termsHelp: "የCustomer መረጃዎ በነባሩ የተረጋገጠ መዳረሻ ህጎች ይጠበቃል።",
    settingsTitle: "ቅንብሮች", language: "ቋንቋ", english: "English", oromo: "Afaan Oromoo", amharic: "አማርኛ", appSettings: "የመተግበሪያ ቅንብሮች",
    notifications: "ማሳወቂያዎች", notificationsHelp: "የማሳወቂያ ባህሪ የbrowser እና HALLO መለያ ቅንብርን ይከተላል።", appearance: "ገጽታ",
    appearanceHelp: "የተፈቀደው የCustomer App ብርሃን ገጽታ ንቁ ነው።", privacy: "ግላዊነት", privacyHelp: "የCustomer መረጃ በገቡበት session እና በነባር RLS ብቻ ይነበባል።",
    about: "ስለ", aboutHelp: "HALLO Smart Logistics Customer App", paymentHistory: "የክፍያ ታሪክ", invoices: "ኢንቮይሶች", refunds: "ተመላሽ ክፍያዎች",
    paymentLedger: "የክፍያ መዝገብ", paymentTruth: "እውነተኛ የክፍያ ክስተቶች ብቻ — የሐሰት wallet balance አይታይም።", noPaymentRecords: "እስካሁን የክፍያ መዝገብ የለም።",
    profileMenu: "መለያ", personalInformation: "የግል መረጃ", savedAddresses: "የተቀመጡ አድራሻዎች", languageSettings: "ቋንቋ እና ቅንብሮች", helpSupport: "እገዛ እና ድጋፍ",
    status: "ሁኔታ", distance: "ርቀት", load: "ጭነት", vehicle: "ተሽከርካሪ", payment: "ክፍያ", driverTruck: "የተመደበ አሽከርካሪ እና መኪና",
    openDetails: "ዝርዝር ክፈት", loading: "በመጫን ላይ…", retry: "እንደገና ሞክር", close: "ዝጋ", refresh: "አድስ", pending: "በመጠባበቅ ላይ",
    stepRouteHelp: "በካርታው ላይ እውነተኛ መነሻና መድረሻ ቦታ ይምረጡ።", stepCargoHelp: "ጭነቱን ይግለጹ እና ትክክለኛውን ክብደት ያስገቡ።",
    stepTruckHelp: "ጭነቱን የሚይዝ አቅም ያለው መኪና ይምረጡ።", stepQuoteHelp: "ከserver የተሰላውን የETB ዋጋ ይገምግሙ።",
    stepReviewHelp: "መንገድ፣ ጭነት፣ መኪና፣ ክፍያ እና ውሎችን ያረጋግጡ።", weightRequired: "ከዜሮ በላይ የጭነት መጠን ያስገቡ።",
    weightExceeds: "ጭነቱ የዚህን መኪና አቅም ይበልጣል።", termsRequired: "ከማረጋገጥዎ በፊት በውሎች እና ሁኔታዎች ይስማሙ።",
    quoteChanged: "የመጓጓዣ ዋጋው ተቀይሯል። የታደሰውን ዋጋ ይገምግሙ እና ደግመው ያረጋግጡ።", noFakeData: "በዚህ ገጽ ላይ ምንም መረጃ በግምት አይፈጠርም።"
  }
} as const;

export function getCustomerFinalCopy(language: CustomerLanguage) {
  return customerFinalCopy[language];
}
