import { useEffect, useState } from "react";

export type CustomerLanguage = "en" | "om" | "am";

const LANGUAGE_KEY = "hallo-customer-language";
const LANGUAGE_EVENT = "hallo-customer-language-change";

export const customerBookingCopy = {
  en: { newBooking:"New booking", findingRoute:"Finding route", bookTrip:"BOOK YOUR TRIP", chooseTruckCargo:"Choose truck & cargo", subtitle:"Select the best vehicle and load details for your delivery.", route:"Route", truck:"Truck", cargo:"Cargo", load:"Load", quote:"Quote", confirm:"Confirm", chooseTruck:"Choose truck type", maxLoad:"Max load", cargoCategory:"Cargo category", packaging:"Packaging / load type", loadAmount:"Load amount", unit:"Unit", notes:"Notes / handling instructions", optional:"Optional", notesHelp:"Optional; does not change the transport quote.", additionalDetails:"Additional cargo details", detailsAdded:"Details added", estimatedQuote:"Estimated quote", currentRate:"Current Admin-managed transport rate.", enterLoad:"Enter the load amount to calculate Birr automatically.", calculating:"Calculating…", calculateQuote:"Calculate Quote", refreshQuote:"Refresh Quote", paymentMethod:"Payment method", cash:"Cash to driver", bankTelebirr:"Bank / Telebirr", confirmOrder:"Confirm Order", submitting:"Creating order…", completeRequired:"Complete every required field and a valid quote to confirm the order.", ready:"Booking details are complete and ready to confirm.", required:"Required" },
  om: { newBooking:"Booking haaraa", findingRoute:"Daandii barbaadaa jira", bookTrip:"GEEJJIBA KEESSAN AJADHAA", chooseTruckCargo:"Konkolaataa fi feʼumsa fili", subtitle:"Geejjiba keessaniif konkolaataa fi ibsa feʼumsaa sirrii fili.", route:"Daandii", truck:"Konkolaataa", cargo:"Feʼumsa", load:"Baayʼina", quote:"Gatii", confirm:"Mirkaneessi", chooseTruck:"Gosa konkolaataa fili", maxLoad:"Feʼumsa olaanaa", cargoCategory:"Gosa feʼumsaa", packaging:"Akkaataa kuusaa / feʼumsaa", loadAmount:"Baayʼina feʼumsaa", unit:"Safartuu", notes:"Yaadannoo / qajeelfama qabannaa", optional:"Filannoo", notesHelp:"Filannoo dha; gatii geejjibaa hin jijjiiru.", additionalDetails:"Ibsa feʼumsaa dabalataa", detailsAdded:"Ibsi dabalameera", estimatedQuote:"Gatii tilmaamaa", currentRate:"Gatii yeroo ammaa bulchiinsi qindeesse.", enterLoad:"Gatiin akka shallagamu baayʼina feʼumsaa galchi.", calculating:"Shallagaa jira…", calculateQuote:"Gatii shallagi", refreshQuote:"Gatii haaromsi", paymentMethod:"Mala kaffaltii", cash:"Maallaqa callaa konkolaachisaaf", bankTelebirr:"Baankii / Telebirr", confirmOrder:"Ajaja mirkaneessi", submitting:"Ajaja uumamaa jira…", completeRequired:"Ajaja mirkaneessuuf dirree barbaachisu hunda fi gatii sirrii guuti.", ready:"Ibsi booking guutameera; mirkaneessuuf qophaaʼeera.", required:"Barbaachisaa" },
  am: { newBooking:"አዲስ ትዕዛዝ", findingRoute:"መንገድ በመፈለግ ላይ", bookTrip:"መጓጓዣዎን ይያዙ", chooseTruckCargo:"መኪና እና ጭነት ይምረጡ", subtitle:"ለማድረሻዎ ተስማሚውን መኪና እና የጭነት ዝርዝር ይምረጡ።", route:"መንገድ", truck:"መኪና", cargo:"ጭነት", load:"መጠን", quote:"ዋጋ", confirm:"ማረጋገጫ", chooseTruck:"የመኪና አይነት ይምረጡ", maxLoad:"ከፍተኛ ጭነት", cargoCategory:"የጭነት ዓይነት", packaging:"የማሸጊያ / የጭነት አይነት", loadAmount:"የጭነት መጠን", unit:"መለኪያ", notes:"ማስታወሻ / የአያያዝ መመሪያ", optional:"አማራጭ", notesHelp:"አማራጭ ነው፤ የመጓጓዣ ዋጋን አይቀይርም።", additionalDetails:"ተጨማሪ የጭነት ዝርዝር", detailsAdded:"ዝርዝር ተጨምሯል", estimatedQuote:"ግምታዊ ዋጋ", currentRate:"አሁን በአስተዳደር የተዘጋጀ ዋጋ።", enterLoad:"ዋጋው እንዲሰላ የጭነት መጠን ያስገቡ።", calculating:"በማስላት ላይ…", calculateQuote:"ዋጋ አስላ", refreshQuote:"ዋጋ አድስ", paymentMethod:"የክፍያ ዘዴ", cash:"ጥሬ ገንዘብ ለአሽከርካሪ", bankTelebirr:"ባንክ / ቴሌብር", confirmOrder:"ትዕዛዝ ያረጋግጡ", submitting:"ትዕዛዝ እየተፈጠረ ነው…", completeRequired:"ትዕዛዙን ለማረጋገጥ ሁሉንም አስፈላጊ መረጃ እና ትክክለኛ ዋጋ ይሙሉ።", ready:"የትዕዛዙ መረጃ ተሟልቷል፤ ለማረጋገጥ ዝግጁ ነው።", required:"አስፈላጊ" },
} as const;

export const customerUiCopy = {
  en: { home:"Home", orders:"Orders", track:"Track", payments:"Payments", profile:"Profile", orderConfirmed:"Order confirmed", dismiss:"Dismiss order confirmation", pickup:"PICKUP PLACE", dropoff:"DROP-OFF PLACE", findPickup:"Find pickup place", findDropoff:"Find delivery place", myLocation:"My location", locating:"Locating…", swap:"Swap", reset:"Reset", startBooking:"Start your booking", startBookingHelp:"Search, use your location, or tap the map to choose pickup and drop-off.", continue:"Continue", routeReady:"Truck route ready", routeSelected:"Route selected", calculatingRoute:"Calculating truck route…", routeUnavailable:"Truck route unavailable", distanceAuto:"AUTO DISTANCE", loadingPhoto:"Loading photo…", assignedDriverTruck:"ASSIGNED DRIVER & TRUCK", assignmentPending:"ASSIGNMENT PENDING", verifiedDriver:"✓ VERIFIED DRIVER", verificationPending:"VERIFICATION PENDING", assignmentMissing:"Assignment details are loading or not available yet.", assignmentNoGuess:"No Driver or truck data is guessed. This card updates only from the secure Customer assignment source.", platePending:"Plate pending", driver:"DRIVER", assignedDriver:"Assigned Driver", phoneUnavailable:"Phone unavailable", photoUnavailable:"One assignment photo could not be loaded. Fallback is shown instead.", assignmentPrivate:"Private assignment details are shown only for this signed-in Customer's order.", liveTracking:"Live trip tracking →" },
  om: { home:"Mana", orders:"Ajajawwan", track:"Hordofi", payments:"Kaffaltii", profile:"Profaayilii", orderConfirmed:"Ajajni mirkanaaʼeera", dismiss:"Beeksisa ajajaa cufi", pickup:"BAKKA KAʼUMSAA", dropoff:"BAKKA GEESSUMSAA", findPickup:"Bakka kaʼumsaa barbaadi", findDropoff:"Bakka geessumsaa barbaadi", myLocation:"Bakka koo", locating:"Bakka kee barbaadaa…", swap:"Wal jijjiiri", reset:"Haqi", startBooking:"Booking jalqabi", startBookingHelp:"Barbaadi, bakka kee fayyadami, ykn bakka kaʼumsaa fi geessumsaa filachuuf kaartaa tuqi.", continue:"Itti fufi", routeReady:"Daandiin konkolaataa qophaaʼeera", routeSelected:"Daandiin filatameera", calculatingRoute:"Daandii konkolaataa shallagaa jira…", routeUnavailable:"Daandiin konkolaataa hin argamne", distanceAuto:"FAGEENYA OFUMAA", loadingPhoto:"Suuraa feʼaa jira…", assignedDriverTruck:"KONKOLAACHISAA FI KONKOLAATAA RAMADAME", assignmentPending:"RAMADAMNI EEGGAMAA JIRA", verifiedDriver:"✓ KONKOLAACHISAA MIRKANAAʼE", verificationPending:"MIRKANEESSI EEGGAMAA JIRA", assignmentMissing:"Odeeffannoon ramaddii feʼamaa jira ykn amma hin jiru.", assignmentNoGuess:"Odeeffannoon konkolaachisaa ykn konkolaataa hin tilmaamamu. Kaardiin kun madda ramaddii Customer nageenya qabu qofa irraa haaromfama.", platePending:"Lakkoofsi gabatee eegamaa jira", driver:"KONKOLAACHISAA", assignedDriver:"Konkolaachisaa ramadame", phoneUnavailable:"Bilbilli hin jiru", photoUnavailable:"Suuraan ramaddii tokko feʼamuu hin dandeenye. Bakka buʼaan agarsiifameera.", assignmentPrivate:"Odeeffannoon ramaddii dhuunfaa ajaja Customer seenee kanaaf qofa agarsiifama.", liveTracking:"Geejjiba kallattiin hordofi →" },
  am: { home:"መነሻ", orders:"ትዕዛዞች", track:"ክትትል", payments:"ክፍያዎች", profile:"መገለጫ", orderConfirmed:"ትዕዛዙ ተረጋግጧል", dismiss:"የትዕዛዝ ማሳወቂያን ዝጋ", pickup:"መነሻ ቦታ", dropoff:"መድረሻ ቦታ", findPickup:"መነሻ ቦታ ይፈልጉ", findDropoff:"መድረሻ ቦታ ይፈልጉ", myLocation:"የእኔ ቦታ", locating:"ቦታዎን በመፈለግ ላይ…", swap:"ቀያይር", reset:"አጽዳ", startBooking:"ትዕዛዝዎን ይጀምሩ", startBookingHelp:"ይፈልጉ፣ ያሉበትን ቦታ ይጠቀሙ ወይም መነሻና መድረሻን ለመምረጥ ካርታውን ይንኩ።", continue:"ቀጥል", routeReady:"የመኪና መንገድ ዝግጁ ነው", routeSelected:"መንገድ ተመርጧል", calculatingRoute:"የመኪና መንገድ በማስላት ላይ…", routeUnavailable:"የመኪና መንገድ አልተገኘም", distanceAuto:"ራስ-ሰር ርቀት", loadingPhoto:"ፎቶ በመጫን ላይ…", assignedDriverTruck:"የተመደበ አሽከርካሪ እና መኪና", assignmentPending:"ምደባ በመጠባበቅ ላይ", verifiedDriver:"✓ የተረጋገጠ አሽከርካሪ", verificationPending:"ማረጋገጫ በመጠባበቅ ላይ", assignmentMissing:"የምደባ መረጃ በመጫን ላይ ነው ወይም ገና አልተገኘም።", assignmentNoGuess:"የአሽከርካሪ ወይም የመኪና መረጃ አይገመትም። ይህ ካርድ ከደህንነቱ የተጠበቀ የCustomer ምደባ ምንጭ ብቻ ይዘምናል።", platePending:"ታርጋ በመጠባበቅ ላይ", driver:"አሽከርካሪ", assignedDriver:"የተመደበ አሽከርካሪ", phoneUnavailable:"ስልክ አልተገኘም", photoUnavailable:"አንድ የምደባ ፎቶ መጫን አልቻለም። ተለዋጭ ምልክት ታይቷል።", assignmentPrivate:"የግል ምደባ መረጃ ለዚህ የገባ Customer ትዕዛዝ ብቻ ይታያል።", liveTracking:"ቀጥታ ጉዞን ይከታተሉ →" },
} as const;

function readLanguage(): CustomerLanguage { const value = window.localStorage.getItem(LANGUAGE_KEY); return value === "en" || value === "am" || value === "om" ? value : "om"; }

export function useCustomerLanguage() {
  const [language, setLanguageState] = useState<CustomerLanguage>(readLanguage);
  useEffect(() => { function syncLanguage(){ setLanguageState(readLanguage()); } window.addEventListener(LANGUAGE_EVENT, syncLanguage); window.addEventListener("storage", syncLanguage); return () => { window.removeEventListener(LANGUAGE_EVENT, syncLanguage); window.removeEventListener("storage", syncLanguage); }; }, []);
  function setLanguage(next: CustomerLanguage) { window.localStorage.setItem(LANGUAGE_KEY, next); document.documentElement.lang = next; setLanguageState(next); window.dispatchEvent(new Event(LANGUAGE_EVENT)); }
  return { language, setLanguage, text: customerBookingCopy[language], ui: customerUiCopy[language] };
}

export function CustomerLanguageSwitcher({ compact = false }: { compact?: boolean }) {
  const { language, setLanguage } = useCustomerLanguage();
  const options: Array<{ value: CustomerLanguage; label: string; title: string }> = [{ value: "en", label: "EN", title: "English" }, { value: "om", label: "OR", title: "Afaan Oromoo" }, { value: "am", label: "አማ", title: "አማርኛ" }];
  return <div className={`customer-language-switcher ${compact ? "is-compact" : ""}`} role="group" aria-label="Language">{options.map((option,index)=><span className="customer-language-choice" key={option.value}>{index>0&&<span className="customer-language-separator" aria-hidden="true">|</span>}<button type="button" className={language===option.value?"is-active":""} aria-pressed={language === option.value} aria-label={option.title} title={option.title} onClick={()=>setLanguage(option.value)}>{option.label}</button></span>)}</div>;
}
