import { type FormEvent,useEffect,useRef,useState } from "react";
import { loadCustomerDriverChatMessages,markCustomerDriverChatRead,openCustomerDriverChat,sendCustomerDriverChatMessage,watchCustomerDriverChat,type CustomerDriverChatMessage } from "./customer-driver-chat.service";

export function CustomerDriverChat({userId,orderId,driverName,onClose}:{userId:string;orderId:string;driverName:string;onClose:()=>void}){
 const[threadId,setThreadId]=useState(""); const[messages,setMessages]=useState<CustomerDriverChatMessage[]>([]); const[me,setMe]=useState(userId); const[text,setText]=useState(""); const[error,setError]=useState(""); const[loading,setLoading]=useState(true); const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{let active=true;let cleanup:(()=>void)|undefined;void(async()=>{try{const id=await openCustomerDriverChat(userId,orderId);if(!active)return;setThreadId(id);const reload=async()=>{const rows=await loadCustomerDriverChatMessages(userId,id);if(active){setMessages(rows);await markCustomerDriverChatRead(userId,id)}};await reload();cleanup=await watchCustomerDriverChat(userId,id,()=>void reload())}catch(e){if(active)setError(e instanceof Error?e.message:"Chat unavailable.")}finally{if(active)setLoading(false)}})();return()=>{active=false;cleanup?.()}},[orderId,userId]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 async function submit(e:FormEvent){e.preventDefault();if(!threadId||!text.trim())return;try{await sendCustomerDriverChatMessage(userId,threadId,text);setText("");setMessages(await loadCustomerDriverChatMessages(userId,threadId))}catch(err){setError(err instanceof Error?err.message:"Message failed.")}}
 return <div className="customer-mobile-chat-backdrop" role="presentation"><section className="customer-mobile-chat" role="dialog" aria-modal="true" aria-label={`Chat with ${driverName}`}><header><div><small>ASSIGNED DRIVER</small><strong>{driverName}</strong></div><button type="button" onClick={onClose} aria-label="Close chat">×</button></header><div className="customer-mobile-chat__messages">{loading&&<p className="customer-mobile-chat__state">Loading secure chat…</p>}{!loading&&!messages.length&&!error&&<p className="customer-mobile-chat__state">Message your assigned driver about this order.</p>}{messages.map(m=><div key={m.id} className={m.sender_id===me?"is-mine":"is-peer"}><p>{m.body}</p><time>{new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></div>)}{error&&<p className="customer-mobile-chat__error">{error}</p>}<div ref={end}/></div><form onSubmit={submit}><input value={text} onChange={e=>setText(e.target.value)} maxLength={4000} placeholder="Message driver…" aria-label="Message driver"/><button type="submit" disabled={!threadId||!text.trim()}>Send</button></form></section></div>
}