const KEY="hallo-customer-language", EVENT="hallo-customer-language-change";
const COPY:Record<"om"|"am",Record<string,string>>={
 om:{"Logistics overview":"Cuunfaa geejjibaa","+ New order":"+ Ajaja haaraa","Orders":"Ajajawwan","Active":"Sochoʼaa","To pay":"Kaffalamu","Delivered":"Geessame","All":"Hunda","Payment":"Kaffaltii","Cancelled":"Haqame","No matching orders":"Ajajni walsimu hin jiru","No orders match this filter.":"Ajajni filannoo kanaan walsimu hin jiru.","Show all":"Hunda agarsiisi","Back to Home":"Gara Manaatti","Pending verification":"Mirkaneessa eegamaa","Pending tracking ID":"Lakkoofsa hordoffii eegamaa","Pending":"Eegamaa","Quote":"Gatii","Distance":"Fageenya","Load":"Feʼumsa","Vehicle":"Konkolaataa","Cash":"Maallaqa callaa","Bank / Telebirr":"Baankii / Telebirr","Invoice / receipt PDF":"Invoice / nagahee PDF","Hide details":"Ibsa dhoksi","View details":"Ibsa ilaali","Open details":"Ibsa guutuu bani","In Transit":"Daandii irra","Placed":"Galmaaʼe","Accepted":"Fudhatame","Assigned":"Ramadame","Completed":"Xumurame","Live trip tracking":"Geejjiba kallattiin hordofi","Cancelling…":"Haqaa jira…","Cancel order":"Ajaja haqi","Cancel this transport order?":"Ajaja geejjibaa kana haqxu?","Cancellation reason":"Sababa haqinsaa","Example: My delivery date or destination changed.":"Fakkeenyaaf: Guyyaan geejjibaa ykn bakki geessuu jijjiirame.","Enter at least 5 characters (maximum 500).":"Yoo xiqqaate qubee 5 galchi (hanga 500).","Keep order":"Ajaja tursiisi","Cancel order with reason":"Sababa waliin ajaja haqi","Verified paid":"Kaffaltiin mirkanaaʼe","PAYMENT HISTORY":"SEENAA KAFFALTII","View receipt":"Nagahee ilaali","No payment history recorded for this order.":"Ajaja kanaaf seenaa kaffaltii galmaaʼe hin jiru.","CUSTOMER MOBILE":"MAAMILA MOOBAAYILAA","Loading your Customer-owned orders and secure assignment cards.":"Ajajawwan maamila kanaa fi kaardii ramaddii nageenya qabu feʼaa jira…"},
 am:{"Logistics overview":"የመጓጓዣ አጠቃላይ እይታ","+ New order":"+ አዲስ ትዕዛዝ","Orders":"ትዕዛዞች","Active":"ንቁ","To pay":"የሚከፈል","Delivered":"ደርሷል","All":"ሁሉም","Payment":"ክፍያ","Cancelled":"ተሰርዟል","No matching orders":"የሚዛመድ ትዕዛዝ የለም","No orders match this filter.":"ከዚህ ማጣሪያ ጋር የሚዛመድ ትዕዛዝ የለም።","Show all":"ሁሉንም አሳይ","Back to Home":"ወደ መነሻ","Pending verification":"ማረጋገጫ በመጠባበቅ ላይ","Pending tracking ID":"የክትትል መለያ በመጠባበቅ ላይ","Pending":"በመጠባበቅ ላይ","Quote":"ዋጋ","Distance":"ርቀት","Load":"ጭነት","Vehicle":"መኪና","Cash":"ጥሬ ገንዘብ","Bank / Telebirr":"ባንክ / ቴሌብር","Invoice / receipt PDF":"ደረሰኝ / ኢንቮይስ PDF","Hide details":"ዝርዝር ደብቅ","View details":"ዝርዝር አሳይ","Open details":"ሙሉ ዝርዝር ክፈት","In Transit":"በመንገድ ላይ","Placed":"ተመዝግቧል","Accepted":"ተቀብሏል","Assigned":"ተመድቧል","Completed":"ተጠናቋል","Live trip tracking":"ቀጥታ ጉዞን ይከታተሉ","Cancelling…":"በመሰረዝ ላይ…","Cancel order":"ትዕዛዝ ሰርዝ","Cancel this transport order?":"ይህን የመጓጓዣ ትዕዛዝ ይሰርዙ?","Cancellation reason":"የስረዛ ምክንያት","Example: My delivery date or destination changed.":"ለምሳሌ፦ የመላኪያ ቀን ወይም መድረሻ ተቀይሯል።","Enter at least 5 characters (maximum 500).":"ቢያንስ 5 ፊደላት ያስገቡ (ከፍተኛ 500)።","Keep order":"ትዕዛዙን አቆይ","Cancel order with reason":"ከምክንያት ጋር ትዕዛዝ ሰርዝ","Verified paid":"የተረጋገጠ ክፍያ","PAYMENT HISTORY":"የክፍያ ታሪክ","View receipt":"ደረሰኝ አሳይ","No payment history recorded for this order.":"ለዚህ ትዕዛዝ የተመዘገበ የክፍያ ታሪክ የለም።","CUSTOMER MOBILE":"የደንበኛ ሞባይል","Loading your Customer-owned orders and secure assignment cards.":"የደንበኛውን ትዕዛዞች እና ደህንነቱ የተጠበቀ የምደባ ካርድ በመጫን ላይ…"}
};
function lang(){const v=localStorage.getItem(KEY);return v==="om"||v==="am"?v:"en";}function run(){const l=lang();if(l==="en")return;const root=document.getElementById("root");if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n:Node|null=w.nextNode();while(n){const r=n.textContent??"",t=r.trim(),x=COPY[l][t];if(x)n.textContent=r.replace(t,x);n=w.nextNode();}}
if(typeof document!=="undefined"){const root=document.getElementById("root");if(root)new MutationObserver(run).observe(root,{childList:true,subtree:true,characterData:true});window.addEventListener(EVENT,()=>queueMicrotask(run));queueMicrotask(run);}

export {};
