import * as React from 'react';
import * as SelectPrimitive from '@radix-ui/react-select';
import { ChevronDown } from 'lucide-react';
import styles from './Select.module.css';
export const Select=SelectPrimitive.Root;
export const SelectValue=SelectPrimitive.Value;
export const SelectTrigger=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Trigger>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger>>(({children,className,...props},ref)=><SelectPrimitive.Trigger ref={ref} className={`${styles.trigger} ${className||''}`} {...props}>{children}<SelectPrimitive.Icon><ChevronDown size={16}/></SelectPrimitive.Icon></SelectPrimitive.Trigger>);
SelectTrigger.displayName='SelectTrigger';
export const SelectContent=({children,...props}:React.ComponentProps<typeof SelectPrimitive.Content>)=><SelectPrimitive.Portal><SelectPrimitive.Content className={styles.content} position="popper" {...props}><SelectPrimitive.Viewport>{children}</SelectPrimitive.Viewport></SelectPrimitive.Content></SelectPrimitive.Portal>;
export const SelectItem=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Item>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Item>>(({children,...props},ref)=><SelectPrimitive.Item ref={ref} className={styles.item} {...props}><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText></SelectPrimitive.Item>);
SelectItem.displayName='SelectItem';
